language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7

branches:
    only:
        - master

before_install:
    - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - source $(conda info --root)/etc/profile.d/conda.sh
        
install:
    - CONDA_RESTORE_FREE_CHANNEL=1 conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
    - conda activate test-environment
    - conda install --yes coverage coveralls flake8
    - pip install pip install pandas
    - pip install numpy
    - pip install maths

before_script:
    - flake8 crystalmaths

script:
    - coverage run -m unittest discover
#     - coverage run test_angles_from_fft.py
#     - coverage run test_angles_from_structure_data.py
#     - coverage run test_distance_from_fft.py
#     - coverage run test_find_matching_angles.py
#     - coverage run test_imagetools.py
#     - coverage run test_trans_mode.py

after_success:
    - coverage report
    - coveralls

