name: crystalmaths
channels:
  - defaults
  - conda-forge
dependencies:
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.2
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cloudpickle=1.3.0
  - colorama=0.4.3
  - cryptography=2.8
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.12.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.8
  - imageio=2.6.1
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.1.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - networkx=2.4
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=1.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pywavelets=1.1.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.1
  - qtpy=1.9.0
  - requests=2.23.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.0.0
  - sip=4.19.8
  - six=1.14.0
  - soupsieve=1.9.5
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
prefix: C:\Users\lacho\.conda\envs\crystalmaths

